//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.21006.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Debuggernaut {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Debuggernaut.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoscroll disabled..
        /// </summary>
        internal static string AutoscrollDisabled {
            get {
                return ResourceManager.GetString("AutoscrollDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoscroll enabled..
        /// </summary>
        internal static string AutoscrollEnabled {
            get {
                return ResourceManager.GetString("AutoscrollEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capturing Output.
        /// </summary>
        internal static string CapturingOutput {
            get {
                return ResourceManager.GetString("CapturingOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capturing Stopped.
        /// </summary>
        internal static string CapturingStopped {
            get {
                return ResourceManager.GetString("CapturingStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DebugOutput.
        /// </summary>
        internal static string DebugOutputFileName {
            get {
                return ResourceManager.GetString("DebugOutputFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude output matching the following pattern:.
        /// </summary>
        internal static string ExcludePatternDescription {
            get {
                return ResourceManager.GetString("ExcludePatternDescription", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Filter {
            get {
                object obj = ResourceManager.GetObject("Filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter reset..
        /// </summary>
        internal static string FilterReset {
            get {
                return ResourceManager.GetString("FilterReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line number ({0}-{1}):.
        /// </summary>
        internal static string GoToLineDescription {
            get {
                return ResourceManager.GetString("GoToLineDescription", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap GreenBall {
            get {
                object obj = ResourceManager.GetObject("GreenBall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight output matching the following pattern:.
        /// </summary>
        internal static string HighlightPatternDescription {
            get {
                return ResourceManager.GetString("HighlightPatternDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include only output matching the following pattern:.
        /// </summary>
        internal static string IncludePatternDescription {
            get {
                return ResourceManager.GetString("IncludePatternDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output cleared..
        /// </summary>
        internal static string OutputCleared {
            get {
                return ResourceManager.GetString("OutputCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added filter on output..
        /// </summary>
        internal static string OutputFilterAdded {
            get {
                return ResourceManager.GetString("OutputFilterAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added highlighting on output..
        /// </summary>
        internal static string OutputHighlightAdded {
            get {
                return ResourceManager.GetString("OutputHighlightAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Starting With &quot;{0}&quot;.
        /// </summary>
        internal static string OutputPrefixMenu {
            get {
                return ResourceManager.GetString("OutputPrefixMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Starting With....
        /// </summary>
        internal static string OutputPrefixMenuDisabled {
            get {
                return ResourceManager.GetString("OutputPrefixMenuDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output saved to {0}.
        /// </summary>
        internal static string OutputSavedTo {
            get {
                return ResourceManager.GetString("OutputSavedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added filter on process ID..
        /// </summary>
        internal static string ProcessIdFilterAdded {
            get {
                return ResourceManager.GetString("ProcessIdFilterAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added highlighting on process ID..
        /// </summary>
        internal static string ProcessIdHighlightAdded {
            get {
                return ResourceManager.GetString("ProcessIdHighlightAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added filter on process name..
        /// </summary>
        internal static string ProcessNameFilterAdded {
            get {
                return ResourceManager.GetString("ProcessNameFilterAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added highlighting on process name..
        /// </summary>
        internal static string ProcessNameHighlightAdded {
            get {
                return ResourceManager.GetString("ProcessNameHighlightAdded", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap RedBall {
            get {
                object obj = ResourceManager.GetObject("RedBall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} rows copied to the clipboard..
        /// </summary>
        internal static string RowsCopied {
            get {
                return ResourceManager.GetString("RowsCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data copied.  Select rows to copy..
        /// </summary>
        internal static string SelectRowsToCopy {
            get {
                return ResourceManager.GetString("SelectRowsToCopy", resourceCulture);
            }
        }
        
        internal static byte[] VirtualTreeGridAssembly {
            get {
                object obj = ResourceManager.GetObject("VirtualTreeGridAssembly", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
